import Head from "next/head";
import {BsFillMoonStarsFill} from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
import React, {useState } from "react";




export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Happy Hounds House</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/dog-favicon.svg" />
      </Head>
      <main className='bg-white dark:bg-gray-900 px-10 md:px-20 lg:px-40'>
      
      <section className='min-h-screen'>
  <video autoPlay muted loop className='absolute top-0 left-0 w-screen h-full object-cover z-0'>
    <source src='/dog-video.mp4' type='video/mp4' />
  </video>
  <div className='absolute top-0 left-0 w-screen h-full bg-black opacity-40'></div>
  <div className='overlay-container relative'>
  <nav className='py-3 md:py-8 mb-2 md:mb-12 flex justify-between dark:text-white z-10'>
  <img src='/dog-logo-gradient.svg' alt='Logo' className='h-10 md:h-20 w-auto text-black' />
  <ul className='flex items-center'>
    <li>
      <a className='bg-gradient-to-r from-orange-500 to-red-500 text-white px-4 py-2 rounded-md ml-4 md:ml-9 font-semibold tracking-wide' href='#'>
        CONTACT
      </a>
    </li>
    <li className='ml-4'>
      <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl'></BsFillMoonStarsFill>
    </li>
  </ul>
</nav>
<div className='text-center py-3 mt-2 md:mt-4 lg:mt-8 xl:mt-12'>
  <Image class="mx-auto" src="/logo-text-alt.svg" width={500} height={500} layout="layout" className="w-25 h-25 md:w-500 md:h-500" />
  <h3 className='text-2xl py-2 text-orange-600 md:text-3xl font-semibold uppercase fade-in'>Dog Minding Services Retreat</h3>
  <p className='text-md py-2 md:py-5 leading-6 text-white max-w-xl mx-auto md:text-xl dark:text-orange-200 fade-in'>
    Welcome to Happy Hounds House, where every pawprint is a joyful journey. Our doggy haven is a shelter from all seasons, offering a hygienic and secure environment, along with expert care and attention. With specially designed areas for play and relaxation, our facility ensures that your pup enjoys each moment to the fullest.
  </p>
</div>
<div className='text-5xl flex justify-center gap-10 py-3 text-orange-600'>
  <AiFillTwitterCircle/>
  <AiFillLinkedin/>
  <AiFillYoutube/>
</div>
</div>
</section>




        <section>
          <div className="flex justify-center items-center">
            <h3 className="text-3xl py-12 px-6 dark:text-white">Our Services</h3>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-orange-400 flex-1">
              <Image class="mx-auto" src="/dog-house.png" width={100} height={100} layout="fixed"/>
              <h3 className="text-lg font-medium pt-8 pb-2">Dog Minding</h3>
              <p className="py-2">
              Our dog minding service offers a safe and comfortable haven for your furry friend. With a team of dedicated caregivers who understand the importance of a nurturing environment, we ensure your dog receives the attention, care, and companionship they deserve.
              </p>
              <Image class="mx-auto" src="/paw-print.png" width={20} height={20} layout="fixed"/>
              <p className="text-gray-800 py-1">Personalized attention</p>
              <p className="text-gray-800 py-1">Safe and secure environment</p>
              <p className="text-gray-800 py-1">Updates and peace of mind</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-orange-400 flex-1">
              <Image class="mx-auto" src="/dog-grooming-icon.png" width={100} height={100} layout="fixed"/>
              <h3 className="text-lg font-medium pt-8 pb-2">Dog Grooming</h3>
              <p className="py-2">
              Indulge your beloved furry friend with our exceptional dog grooming services that redefine pampering. Our expert groomers provide a nurturing and revitalizing experience, leaving your dog looking and feeling their best. 
              </p>
              <Image class="mx-auto" src="/paw-print.png" width={20} height={20} layout="fixed"/>
              <p className="text-gray-800 py-1">Tailored styling + breed-specific trims</p>
              <p className="text-gray-800 py-1">Highest quality products used</p>
              <p className="text-gray-800 py-1">Doggy massages for extra stress relief</p>
            </div>
                        <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-orange-400 flex-1">
              <Image class="mx-auto" src="/trainer.png" width={100} height={100} layout="layout"/>
              <h3 className="text-lg font-medium pt-8 pb-2">Dog Training</h3>
              <p className="py-2">
              Unlock the true potential of your canine companion with our professional dog training services. Our skilled trainers are dedicated to fostering a strong bond between you and your dog while imparting essential skills that enhance their behavior and obedience.
              </p>
              <Image class="mx-auto" src="/paw-print.png" width={20} height={20} layout="fixed"/>
              <p className="text-gray-800 py-1">Solo and group sessions</p>
              <p className="text-gray-800 py-1">Customized training plans</p>
              <p className="text-gray-800 py-1">Socialization and lifelong learning</p>
            </div>
          </div>
        </section>
        <section>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
            <Image src="/pug.svg" className="rounded-lg object-cover" width={300} height={200} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
            <Image src="/sarah-review.svg" className="rounded-lg object-cover" width={300} height={200} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
            <Image src="/david-review.svg" className="rounded-lg object-cover" width={300} height={200} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
            <Image src="/husky.svg" className="rounded-lg object-cover" width={300} height={200} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
            <Image src="/dog-grooming.svg" className="rounded-lg object-cover" width={300} height={200} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
            <Image src="/onur-review.svg" className="rounded-lg object-cover" width={300} height={200} layout="responsive"/>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
